// This file is for local development.
// In a production environment, this file would be generated by a CI/CD pipeline.

window.ENV = window.ENV || {};
window.ENV.API_BASE_URL = "http://localhost:4000/api";
