// For local development, copy this file to `env.js` and set the backend URL.
// In production, `env.js` should be generated by the CI/CD pipeline.
window.ENV = window.ENV || {};
window.ENV.API_BASE_URL = "https://backend.finverge.madebyelio.com/api";


